### ISSUE TITLE
train

### ISSUE THREAD

**Issue by maozhenguo666** [liujf69/ICMEW2024-Track10#2]
how to train

**Comment by liujf69** [comment]
Please refer to the latest [README.md](https://github.com/liujf69/ICMEW2024-Track10/blob/main/README.md).  
Change the configuration file (.yaml) of the corresponding modality.

# Model training
```
# Mix_GCN Example
cd ./Model_inference/Mix_GCN
python main.py --config ./config/ctrgcn_V1_J.yaml --device 0

# Mix_Former Example
cd ./Model_inference/Mix_Former
python main.py --config ./config/mixformer_V1_J.yaml --device 0
```

**Comment by maozhenguo666** [comment]
Where is the training dataset located?

**Comment by maozhenguo666** [comment]
V1.npz and V2.npz are testing dataset

**Comment by maozhenguo666** [comment]
如果我有我自己的数据集，也想拿你的末影箱训练可以嘛，我想拿uav－human数据集训练，重新改进模型训练我该如何操作呢



---Original---
From: "Jinfu ***@***.***&gt;
Date: Fri, Sep 20, 2024 09:17 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [liujf69/ICMEW2024-Track10] train (Issue #2)




 
Please refer to the latest README.md.
 Change the configuration file (.yaml) of the corresponding modality.
 
Model training
 # Mix_GCN Example cd ./Model_inference/Mix_GCN python main.py --config ./config/ctrgcn_V1_J.yaml --device 0 # Mix_Former Example cd ./Model_inference/Mix_Former python main.py --config ./config/mixformer_V1_J.yaml --device 0

**Comment by liujf69** [comment]
参考[extract_2dpose.py](https://github.com/liujf69/ICMEW2024-Track10/blob/main/Process_data/extract_2dpose.py)来提取训练集和验证集，训练集只需要取消注释部分代码即可，例如：
```python
# CS_train_V1_data = []
# CS_train_V1_label = []
# CS_train_V2_data = []
# CS_train_V2_label = []

# V1
# if subj_id in CS_train_V1:
#     CS_train_V1_data.append(pad_data)
#     CS_train_V1_label.append(label)
# else:
#     CS_test_V1_data.append(pad_data)
#     CS_test_V1_label.append(label)

# # V2    
# if subj_id in CS_train_V2:
#     CS_train_V2_data.append(pad_data)
#     CS_train_V2_label.append(label)
# else:
#     CS_test_V2_data.append(pad_data)
#     CS_test_V2_label.append(label)

# CS_train_V1_data = np.array(CS_train_V1_data)
# CS_train_V1_label = np.array(CS_train_V1_label)
# CS_train_V2_data = np.array(CS_train_V2_data)
# CS_train_V2_label = np.array(CS_train_V2_label)

# np.savez('./pose_data/V1.npz', x_train = CS_train_V1_data, y_train = CS_train_V1_label, 
#          x_test = CS_test_V1_data, y_test = CS_test_V1_label)
# np.savez('./pose_data/V2.npz', x_train = CS_train_V2_data, y_train = CS_train_V2_label, 
#          x_test = CS_test_V2_data, y_test = CS_test_V2_label)

# 注释以下只保存测试集的代码：
np.savez('./save_2d_pose/V1.npz', x_test = CS_test_V1_data, y_test = CS_test_V1_label)
np.savez('./save_2d_pose/V2.npz', x_test = CS_test_V2_data, y_test = CS_test_V2_label)
```
