### ISSUE TITLE
 Training Issues

### ISSUE THREAD

**Issue by tanxiaoke6** [liujf69/ICMEW2024-Track10#4]
Hello, thank you very much for open-sourcing this code; it’s a great piece of work. I have some questions about the training process that I would like to ask you. When I trained using my own dataset, I found that my GPU utilization is only around 25%. Is this normal? If not, what steps should I take to resolve this issue?
![屏幕截图 2024-10-02 181322](https://github.com/user-attachments/assets/6cffca60-d007-4a58-9435-e3fcb59f20e0)

**Comment by liujf69** [comment]
Thanks for your question!
The reason for the low GPU utilization is that the code uses ```data parallelism``` (```nn.DataParallel()```). 
To improve GPU utilization, you can switch to distributed training.

**Comment by tanxiaoke6** [comment]
OK，thank you for your reply.
